title: Omar Sierra
logo: "/images/68754fb7063a6b84dd9f225b5381815a.png.jpg?raw=true" # your photo (or logo) here
 <a href="https://github.com/osierra123"> 
  theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
